### ISSUE TITLE
Initial TODO

### ISSUE THREAD

**Issue by algrebe** [deep-compute/go-nsq-throttled-producer#1]
- [ ] Add lower and upper watermark with callback support
- [ ] Add test cases
- [ ] Add godoc and examples
